//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDLV
    {
        public string gv { get; set; }
        public string hd { get; set; }
        public string vaitro { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HDBVLV HDBVLV { get; set; }
    }
}
