//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeTaiLV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeTaiLV()
        {
            this.HDDCs = new HashSet<HDDC>();
            this.HDLVs = new HashSet<HDLV>();
            this.HuongDans = new HashSet<HuongDan>();
        }
    
        public string lv { get; set; }
        public string cm { get; set; }
        public string qd { get; set; }
        public string cn { get; set; }
        public string hv { get; set; }
        public string lvloai { get; set; }
        public string nk { get; set; }
        public string lvten { get; set; }
        public string lvtomtat { get; set; }
        public Nullable<System.DateTime> lvngaynop { get; set; }
        public string lvluutru { get; set; }
        public string status { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual HocVien HocVien { get; set; }
        public virtual LinhVucChuyenMon LinhVucChuyenMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDDC> HDDCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDLV> HDLVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuongDan> HuongDans { get; set; }
    }
}
