//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEMLV
    {
        public string mahd { get; set; }
        public string lv { get; set; }
        public string gv { get; set; }
        public Nullable<float> diem { get; set; }
        public string danhgia { get; set; }
    }
}
