//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.CTHDDCs = new HashSet<CTHDDC>();
            this.CTHDLVs = new HashSet<CTHDLV>();
            this.HuongDans = new HashSet<HuongDan>();
            this.PhanQuyens = new HashSet<PhanQuyen>();
            this.LinhVucChuyenMons = new HashSet<LinhVucChuyenMon>();
        }
    
        public string gv { get; set; }
        public string dv { get; set; }
        public string bm { get; set; }
        public string gvhoten { get; set; }
        public string gvgioitinh { get; set; }
        public string gvchucdanh { get; set; }
        public Nullable<System.DateTime> gvnamcongtac { get; set; }
        public string gvquoctich { get; set; }
        public Nullable<System.DateTime> gvngaysinh { get; set; }
        public string gvnoio { get; set; }
        public string gvsodienthoai { get; set; }
        public string gveil { get; set; }
        public string gvhinhanh { get; set; }
        public string gvtkhau { get; set; }
        public string status { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
    
        public virtual BoMon BoMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDDC> CTHDDCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDLV> CTHDLVs { get; set; }
        public virtual DonViNgoai DonViNgoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuongDan> HuongDans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinhVucChuyenMon> LinhVucChuyenMons { get; set; }
    }
}
