//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBVLV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDBVLV()
        {
            this.CTHDLVs = new HashSet<CTHDLV>();
            this.HDLVs = new HashSet<HDLV>();
        }
    
        public string hd { get; set; }
        public string hdten { get; set; }
        public System.DateTime hdngaythanhlap { get; set; }
        public Nullable<System.DateTime> hdngayketthuc { get; set; }
        public string hddiadiem { get; set; }
        public Nullable<System.DateTime> hdthoigian { get; set; }
        public string status { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDLV> CTHDLVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDLV> HDLVs { get; set; }
    }
}
