//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDBVDC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDBVDC()
        {
            this.CTHDDCs = new HashSet<CTHDDC>();
            this.HDDCs = new HashSet<HDDC>();
        }
    
        public string dc { get; set; }
        public string dcten { get; set; }
        public System.DateTime dcngaythanhlap { get; set; }
        public Nullable<System.DateTime> dcngayketthuc { get; set; }
        public string dcdiadiem { get; set; }
        public Nullable<System.DateTime> dcthoigian { get; set; }
        public string status { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDDC> CTHDDCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDDC> HDDCs { get; set; }
    }
}
