//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDC
    {
        public string dc { get; set; }
        public string lv { get; set; }
        public Nullable<short> lanbaove { get; set; }
        public string ykien { get; set; }
        public string ketqua { get; set; }
        public Nullable<int> sophieudat { get; set; }
        public Nullable<float> diem { get; set; }
        public Nullable<System.DateTime> thoidiembvdc { get; set; }
    
        public virtual DeTaiLV DeTaiLV { get; set; }
        public virtual HDBVDC HDBVDC { get; set; }
    }
}
