//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDLV
    {
        public string hd { get; set; }
        public string lv { get; set; }
        public Nullable<float> diem { get; set; }
        public string ykien { get; set; }
        public string ketqua { get; set; }
        public Nullable<short> lanbaove { get; set; }
        public Nullable<short> sophieudat { get; set; }
        public Nullable<System.DateTime> thoidiembv { get; set; }
    
        public virtual DeTaiLV DeTaiLV { get; set; }
        public virtual HDBVLV HDBVLV { get; set; }
    }
}
