//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocCN
    {
        public string hv { get; set; }
        public string cn { get; set; }
        public string nk { get; set; }
        public string lv { get; set; }
    
        public virtual ChuyenNganh ChuyenNganh { get; set; }
        public virtual HocVien HocVien { get; set; }
        public virtual NienKhoa NienKhoa { get; set; }
    }
}
