//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocVien()
        {
            this.DeTaiLVs = new HashSet<DeTaiLV>();
            this.HocCNs = new HashSet<HocCN>();
        }
    
        public string hv { get; set; }
        public string hvhoten { get; set; }
        public string hvgioitinh { get; set; }
        public Nullable<System.DateTime> hvngaysinh { get; set; }
        public Nullable<System.DateTime> hvngaydkdt { get; set; }
        public Nullable<System.DateTime> hvngaydkbv { get; set; }
        public string hvquequan { get; set; }
        public string hvsodienthoai { get; set; }
        public string hveil { get; set; }
        public string hvhinhanh { get; set; }
        public string hvtkhau { get; set; }
        public string status { get; set; }
        public string createby { get; set; }
        public string modifyby { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<System.DateTime> mtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeTaiLV> DeTaiLVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocCN> HocCNs { get; set; }
    }
}
