//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class thsContext : DbContext
    {
        public thsContext()
            : base("name=thsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMons { get; set; }
        public virtual DbSet<ChuyenNganh> ChuyenNganhs { get; set; }
        public virtual DbSet<CTHDDC> CTHDDCs { get; set; }
        public virtual DbSet<CTHDLV> CTHDLVs { get; set; }
        public virtual DbSet<DeTaiLV> DeTaiLVs { get; set; }
        public virtual DbSet<DIEMLV> DIEMLVs { get; set; }
        public virtual DbSet<DonViNgoai> DonViNgoais { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HDBVDC> HDBVDCs { get; set; }
        public virtual DbSet<HDBVLV> HDBVLVs { get; set; }
        public virtual DbSet<HDDC> HDDCs { get; set; }
        public virtual DbSet<HDLV> HDLVs { get; set; }
        public virtual DbSet<HocCN> HocCNs { get; set; }
        public virtual DbSet<HocVien> HocViens { get; set; }
        public virtual DbSet<HuongDan> HuongDans { get; set; }
        public virtual DbSet<LinhVucChuyenMon> LinhVucChuyenMons { get; set; }
        public virtual DbSet<NienKhoa> NienKhoas { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<Tcode> Tcodes { get; set; }
    
        public virtual int ADC_store(string st)
        {
            var stParameter = st != null ?
                new ObjectParameter("st", st) :
                new ObjectParameter("st", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADC_store", stParameter);
        }
    
        public virtual int AuthLogin(string username, string pass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AuthLogin", usernameParameter, passParameter);
        }
    
        public virtual ObjectResult<string> ChangePassword(string username, string pass, string newpass)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var newpassParameter = newpass != null ?
                new ObjectParameter("newpass", newpass) :
                new ObjectParameter("newpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ChangePassword", usernameParameter, passParameter, newpassParameter);
        }
    
        public virtual ObjectResult<CheckTCode_Result> CheckTCode(string username, string tcode)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var tcodeParameter = tcode != null ?
                new ObjectParameter("tcode", tcode) :
                new ObjectParameter("tcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckTCode_Result>("CheckTCode", usernameParameter, tcodeParameter);
        }
    
        public virtual int CRUD_CMGV(string action, string gv, string cm)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var cmParameter = cm != null ?
                new ObjectParameter("cm", cm) :
                new ObjectParameter("cm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUD_CMGV", actionParameter, gvParameter, cmParameter);
        }
    
        public virtual ObjectResult<CRUD_CTHDDC_Result> CRUD_CTHDDC(string action, string dc, string gv, string vaitro)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var vaitroParameter = vaitro != null ?
                new ObjectParameter("vaitro", vaitro) :
                new ObjectParameter("vaitro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_CTHDDC_Result>("CRUD_CTHDDC", actionParameter, dcParameter, gvParameter, vaitroParameter);
        }
    
        public virtual ObjectResult<CRUD_CTHDLV_Result> CRUD_CTHDLV(string action, string hd, string gv, string vaitro)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var vaitroParameter = vaitro != null ?
                new ObjectParameter("vaitro", vaitro) :
                new ObjectParameter("vaitro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CRUD_CTHDLV_Result>("CRUD_CTHDLV", actionParameter, hdParameter, gvParameter, vaitroParameter);
        }
    
        public virtual int CRUD_HDDC(string action, string dc, string lv, Nullable<short> lanbaove, Nullable<double> diem, string ykien, string ketqua, Nullable<short> sophieudat, Nullable<System.DateTime> thoidiembvdc)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var lanbaoveParameter = lanbaove.HasValue ?
                new ObjectParameter("lanbaove", lanbaove) :
                new ObjectParameter("lanbaove", typeof(short));
    
            var diemParameter = diem.HasValue ?
                new ObjectParameter("diem", diem) :
                new ObjectParameter("diem", typeof(double));
    
            var ykienParameter = ykien != null ?
                new ObjectParameter("ykien", ykien) :
                new ObjectParameter("ykien", typeof(string));
    
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            var sophieudatParameter = sophieudat.HasValue ?
                new ObjectParameter("sophieudat", sophieudat) :
                new ObjectParameter("sophieudat", typeof(short));
    
            var thoidiembvdcParameter = thoidiembvdc.HasValue ?
                new ObjectParameter("thoidiembvdc", thoidiembvdc) :
                new ObjectParameter("thoidiembvdc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUD_HDDC", actionParameter, dcParameter, lvParameter, lanbaoveParameter, diemParameter, ykienParameter, ketquaParameter, sophieudatParameter, thoidiembvdcParameter);
        }
    
        public virtual int CRUD_HDLV(string action, string hd, string lv, Nullable<short> lanbaove, Nullable<double> diem, string ykien, string ketqua, Nullable<short> sophieudat, Nullable<System.DateTime> thoidiembv)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var lanbaoveParameter = lanbaove.HasValue ?
                new ObjectParameter("lanbaove", lanbaove) :
                new ObjectParameter("lanbaove", typeof(short));
    
            var diemParameter = diem.HasValue ?
                new ObjectParameter("diem", diem) :
                new ObjectParameter("diem", typeof(double));
    
            var ykienParameter = ykien != null ?
                new ObjectParameter("ykien", ykien) :
                new ObjectParameter("ykien", typeof(string));
    
            var ketquaParameter = ketqua != null ?
                new ObjectParameter("ketqua", ketqua) :
                new ObjectParameter("ketqua", typeof(string));
    
            var sophieudatParameter = sophieudat.HasValue ?
                new ObjectParameter("sophieudat", sophieudat) :
                new ObjectParameter("sophieudat", typeof(short));
    
            var thoidiembvParameter = thoidiembv.HasValue ?
                new ObjectParameter("thoidiembv", thoidiembv) :
                new ObjectParameter("thoidiembv", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUD_HDLV", actionParameter, hdParameter, lvParameter, lanbaoveParameter, diemParameter, ykienParameter, ketquaParameter, sophieudatParameter, thoidiembvParameter);
        }
    
        public virtual int CRUD_HocCN(string action, string hv, string cn, string nk)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var cnParameter = cn != null ?
                new ObjectParameter("cn", cn) :
                new ObjectParameter("cn", typeof(string));
    
            var nkParameter = nk != null ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUD_HocCN", actionParameter, hvParameter, cnParameter, nkParameter);
        }
    
        public virtual int CRUD_HuongDan(string action, string lv, string gv, string vaitrohuongdan)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var vaitrohuongdanParameter = vaitrohuongdan != null ?
                new ObjectParameter("vaitrohuongdan", vaitrohuongdan) :
                new ObjectParameter("vaitrohuongdan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CRUD_HuongDan", actionParameter, lvParameter, gvParameter, vaitrohuongdanParameter);
        }
    
        public virtual ObjectResult<CUD_BoMon_Result> CUD_BoMon(string action, string bm, string bmnew, string bmten)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var bmnewParameter = bmnew != null ?
                new ObjectParameter("bmnew", bmnew) :
                new ObjectParameter("bmnew", typeof(string));
    
            var bmtenParameter = bmten != null ?
                new ObjectParameter("bmten", bmten) :
                new ObjectParameter("bmten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CUD_BoMon_Result>("CUD_BoMon", actionParameter, bmParameter, bmnewParameter, bmtenParameter);
        }
    
        public virtual ObjectResult<CUD_ChuyenNganh_Result> CUD_ChuyenNganh(string action, string cn, string cnnew, string bm, string cnten)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var cnParameter = cn != null ?
                new ObjectParameter("cn", cn) :
                new ObjectParameter("cn", typeof(string));
    
            var cnnewParameter = cnnew != null ?
                new ObjectParameter("cnnew", cnnew) :
                new ObjectParameter("cnnew", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var cntenParameter = cnten != null ?
                new ObjectParameter("cnten", cnten) :
                new ObjectParameter("cnten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CUD_ChuyenNganh_Result>("CUD_ChuyenNganh", actionParameter, cnParameter, cnnewParameter, bmParameter, cntenParameter);
        }
    
        public virtual ObjectResult<string> CUD_DeTaiLV(string action, string lv, string cm, string qd, string cn, string hv, string lvloai, string nk, string lvten, string lvtomtat, Nullable<System.DateTime> lvngaynop, string lvluutru, string status, string user)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var cmParameter = cm != null ?
                new ObjectParameter("cm", cm) :
                new ObjectParameter("cm", typeof(string));
    
            var qdParameter = qd != null ?
                new ObjectParameter("qd", qd) :
                new ObjectParameter("qd", typeof(string));
    
            var cnParameter = cn != null ?
                new ObjectParameter("cn", cn) :
                new ObjectParameter("cn", typeof(string));
    
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var lvloaiParameter = lvloai != null ?
                new ObjectParameter("lvloai", lvloai) :
                new ObjectParameter("lvloai", typeof(string));
    
            var nkParameter = nk != null ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(string));
    
            var lvtenParameter = lvten != null ?
                new ObjectParameter("lvten", lvten) :
                new ObjectParameter("lvten", typeof(string));
    
            var lvtomtatParameter = lvtomtat != null ?
                new ObjectParameter("lvtomtat", lvtomtat) :
                new ObjectParameter("lvtomtat", typeof(string));
    
            var lvngaynopParameter = lvngaynop.HasValue ?
                new ObjectParameter("lvngaynop", lvngaynop) :
                new ObjectParameter("lvngaynop", typeof(System.DateTime));
    
            var lvluutruParameter = lvluutru != null ?
                new ObjectParameter("lvluutru", lvluutru) :
                new ObjectParameter("lvluutru", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CUD_DeTaiLV", actionParameter, lvParameter, cmParameter, qdParameter, cnParameter, hvParameter, lvloaiParameter, nkParameter, lvtenParameter, lvtomtatParameter, lvngaynopParameter, lvluutruParameter, statusParameter, userParameter);
        }
    
        public virtual ObjectResult<CUD_DonViNgoai_Result> CUD_DonViNgoai(string action, string dv, string dvnew, string dvten, string dvdiachi, string dvsdt, string dveil)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            var dvnewParameter = dvnew != null ?
                new ObjectParameter("dvnew", dvnew) :
                new ObjectParameter("dvnew", typeof(string));
    
            var dvtenParameter = dvten != null ?
                new ObjectParameter("dvten", dvten) :
                new ObjectParameter("dvten", typeof(string));
    
            var dvdiachiParameter = dvdiachi != null ?
                new ObjectParameter("dvdiachi", dvdiachi) :
                new ObjectParameter("dvdiachi", typeof(string));
    
            var dvsdtParameter = dvsdt != null ?
                new ObjectParameter("dvsdt", dvsdt) :
                new ObjectParameter("dvsdt", typeof(string));
    
            var dveilParameter = dveil != null ?
                new ObjectParameter("dveil", dveil) :
                new ObjectParameter("dveil", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CUD_DonViNgoai_Result>("CUD_DonViNgoai", actionParameter, dvParameter, dvnewParameter, dvtenParameter, dvdiachiParameter, dvsdtParameter, dveilParameter);
        }
    
        public virtual ObjectResult<string> CUD_GiangVien(string action, string gv, string dv, string bm, string gvhoten, string gvgioitinh, string gvchucdanh, Nullable<System.DateTime> gvnamcongtac, string gvquoctich, Nullable<System.DateTime> gvngaysinh, string gvnoio, string gvsodienthoai, string gveil, string gvhinhanh, string user)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var gvhotenParameter = gvhoten != null ?
                new ObjectParameter("gvhoten", gvhoten) :
                new ObjectParameter("gvhoten", typeof(string));
    
            var gvgioitinhParameter = gvgioitinh != null ?
                new ObjectParameter("gvgioitinh", gvgioitinh) :
                new ObjectParameter("gvgioitinh", typeof(string));
    
            var gvchucdanhParameter = gvchucdanh != null ?
                new ObjectParameter("gvchucdanh", gvchucdanh) :
                new ObjectParameter("gvchucdanh", typeof(string));
    
            var gvnamcongtacParameter = gvnamcongtac.HasValue ?
                new ObjectParameter("gvnamcongtac", gvnamcongtac) :
                new ObjectParameter("gvnamcongtac", typeof(System.DateTime));
    
            var gvquoctichParameter = gvquoctich != null ?
                new ObjectParameter("gvquoctich", gvquoctich) :
                new ObjectParameter("gvquoctich", typeof(string));
    
            var gvngaysinhParameter = gvngaysinh.HasValue ?
                new ObjectParameter("gvngaysinh", gvngaysinh) :
                new ObjectParameter("gvngaysinh", typeof(System.DateTime));
    
            var gvnoioParameter = gvnoio != null ?
                new ObjectParameter("gvnoio", gvnoio) :
                new ObjectParameter("gvnoio", typeof(string));
    
            var gvsodienthoaiParameter = gvsodienthoai != null ?
                new ObjectParameter("gvsodienthoai", gvsodienthoai) :
                new ObjectParameter("gvsodienthoai", typeof(string));
    
            var gveilParameter = gveil != null ?
                new ObjectParameter("gveil", gveil) :
                new ObjectParameter("gveil", typeof(string));
    
            var gvhinhanhParameter = gvhinhanh != null ?
                new ObjectParameter("gvhinhanh", gvhinhanh) :
                new ObjectParameter("gvhinhanh", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CUD_GiangVien", actionParameter, gvParameter, dvParameter, bmParameter, gvhotenParameter, gvgioitinhParameter, gvchucdanhParameter, gvnamcongtacParameter, gvquoctichParameter, gvngaysinhParameter, gvnoioParameter, gvsodienthoaiParameter, gveilParameter, gvhinhanhParameter, userParameter);
        }
    
        public virtual ObjectResult<string> CUD_HDBVDC(string action, string dc, string dcten, Nullable<System.DateTime> dcngaythanhlap, Nullable<System.DateTime> dcngayketthuc, string dcdiadiem, Nullable<System.DateTime> dcthoigian, string user)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var dctenParameter = dcten != null ?
                new ObjectParameter("dcten", dcten) :
                new ObjectParameter("dcten", typeof(string));
    
            var dcngaythanhlapParameter = dcngaythanhlap.HasValue ?
                new ObjectParameter("dcngaythanhlap", dcngaythanhlap) :
                new ObjectParameter("dcngaythanhlap", typeof(System.DateTime));
    
            var dcngayketthucParameter = dcngayketthuc.HasValue ?
                new ObjectParameter("dcngayketthuc", dcngayketthuc) :
                new ObjectParameter("dcngayketthuc", typeof(System.DateTime));
    
            var dcdiadiemParameter = dcdiadiem != null ?
                new ObjectParameter("dcdiadiem", dcdiadiem) :
                new ObjectParameter("dcdiadiem", typeof(string));
    
            var dcthoigianParameter = dcthoigian.HasValue ?
                new ObjectParameter("dcthoigian", dcthoigian) :
                new ObjectParameter("dcthoigian", typeof(System.DateTime));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CUD_HDBVDC", actionParameter, dcParameter, dctenParameter, dcngaythanhlapParameter, dcngayketthucParameter, dcdiadiemParameter, dcthoigianParameter, userParameter);
        }
    
        public virtual ObjectResult<string> CUD_HDBVLV(string action, string hd, string hdten, Nullable<System.DateTime> hdngaythanhlap, Nullable<System.DateTime> hdngayketthuc, string hddiadiem, Nullable<System.DateTime> hdthoigian, string user)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var hdtenParameter = hdten != null ?
                new ObjectParameter("hdten", hdten) :
                new ObjectParameter("hdten", typeof(string));
    
            var hdngaythanhlapParameter = hdngaythanhlap.HasValue ?
                new ObjectParameter("hdngaythanhlap", hdngaythanhlap) :
                new ObjectParameter("hdngaythanhlap", typeof(System.DateTime));
    
            var hdngayketthucParameter = hdngayketthuc.HasValue ?
                new ObjectParameter("hdngayketthuc", hdngayketthuc) :
                new ObjectParameter("hdngayketthuc", typeof(System.DateTime));
    
            var hddiadiemParameter = hddiadiem != null ?
                new ObjectParameter("hddiadiem", hddiadiem) :
                new ObjectParameter("hddiadiem", typeof(string));
    
            var hdthoigianParameter = hdthoigian.HasValue ?
                new ObjectParameter("hdthoigian", hdthoigian) :
                new ObjectParameter("hdthoigian", typeof(System.DateTime));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CUD_HDBVLV", actionParameter, hdParameter, hdtenParameter, hdngaythanhlapParameter, hdngayketthucParameter, hddiadiemParameter, hdthoigianParameter, userParameter);
        }
    
        public virtual ObjectResult<string> CUD_HocVien(string action, string hv, string hvhoten, string hvgioitinh, Nullable<System.DateTime> hvngaysinh, Nullable<System.DateTime> hvngaydkdt, Nullable<System.DateTime> hvngaydkbv, string hvquequan, string hvsodienthoai, string hveil, string hvhinhanh, string user)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var hvhotenParameter = hvhoten != null ?
                new ObjectParameter("hvhoten", hvhoten) :
                new ObjectParameter("hvhoten", typeof(string));
    
            var hvgioitinhParameter = hvgioitinh != null ?
                new ObjectParameter("hvgioitinh", hvgioitinh) :
                new ObjectParameter("hvgioitinh", typeof(string));
    
            var hvngaysinhParameter = hvngaysinh.HasValue ?
                new ObjectParameter("hvngaysinh", hvngaysinh) :
                new ObjectParameter("hvngaysinh", typeof(System.DateTime));
    
            var hvngaydkdtParameter = hvngaydkdt.HasValue ?
                new ObjectParameter("hvngaydkdt", hvngaydkdt) :
                new ObjectParameter("hvngaydkdt", typeof(System.DateTime));
    
            var hvngaydkbvParameter = hvngaydkbv.HasValue ?
                new ObjectParameter("hvngaydkbv", hvngaydkbv) :
                new ObjectParameter("hvngaydkbv", typeof(System.DateTime));
    
            var hvquequanParameter = hvquequan != null ?
                new ObjectParameter("hvquequan", hvquequan) :
                new ObjectParameter("hvquequan", typeof(string));
    
            var hvsodienthoaiParameter = hvsodienthoai != null ?
                new ObjectParameter("hvsodienthoai", hvsodienthoai) :
                new ObjectParameter("hvsodienthoai", typeof(string));
    
            var hveilParameter = hveil != null ?
                new ObjectParameter("hveil", hveil) :
                new ObjectParameter("hveil", typeof(string));
    
            var hvhinhanhParameter = hvhinhanh != null ?
                new ObjectParameter("hvhinhanh", hvhinhanh) :
                new ObjectParameter("hvhinhanh", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CUD_HocVien", actionParameter, hvParameter, hvhotenParameter, hvgioitinhParameter, hvngaysinhParameter, hvngaydkdtParameter, hvngaydkbvParameter, hvquequanParameter, hvsodienthoaiParameter, hveilParameter, hvhinhanhParameter, userParameter);
        }
    
        public virtual ObjectResult<CUD_LinhVucChuyenMon_Result> CUD_LinhVucChuyenMon(string action, string cm, string cmnew, string cmten)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var cmParameter = cm != null ?
                new ObjectParameter("cm", cm) :
                new ObjectParameter("cm", typeof(string));
    
            var cmnewParameter = cmnew != null ?
                new ObjectParameter("cmnew", cmnew) :
                new ObjectParameter("cmnew", typeof(string));
    
            var cmtenParameter = cmten != null ?
                new ObjectParameter("cmten", cmten) :
                new ObjectParameter("cmten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CUD_LinhVucChuyenMon_Result>("CUD_LinhVucChuyenMon", actionParameter, cmParameter, cmnewParameter, cmtenParameter);
        }
    
        public virtual ObjectResult<CUD_NienKhoa_Result> CUD_NienKhoa(string action, string nk, string nknew, string nkten, string nknam, Nullable<System.DateTime> nktungay, Nullable<System.DateTime> nkdenngay)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var nkParameter = nk != null ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(string));
    
            var nknewParameter = nknew != null ?
                new ObjectParameter("nknew", nknew) :
                new ObjectParameter("nknew", typeof(string));
    
            var nktenParameter = nkten != null ?
                new ObjectParameter("nkten", nkten) :
                new ObjectParameter("nkten", typeof(string));
    
            var nknamParameter = nknam != null ?
                new ObjectParameter("nknam", nknam) :
                new ObjectParameter("nknam", typeof(string));
    
            var nktungayParameter = nktungay.HasValue ?
                new ObjectParameter("nktungay", nktungay) :
                new ObjectParameter("nktungay", typeof(System.DateTime));
    
            var nkdenngayParameter = nkdenngay.HasValue ?
                new ObjectParameter("nkdenngay", nkdenngay) :
                new ObjectParameter("nkdenngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CUD_NienKhoa_Result>("CUD_NienKhoa", actionParameter, nkParameter, nknewParameter, nktenParameter, nknamParameter, nktungayParameter, nkdenngayParameter);
        }
    
        public virtual ObjectResult<GetBasic_Result> GetBasic(string table, string bm)
        {
            var tableParameter = table != null ?
                new ObjectParameter("Table", table) :
                new ObjectParameter("Table", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBasic_Result>("GetBasic", tableParameter, bmParameter);
        }
    
        public virtual ObjectResult<GetByID_Result> GetByID(string table, string value)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByID_Result>("GetByID", tableParameter, valueParameter);
        }
    
        public virtual ObjectResult<SearchGiangVien_Result> SearchGiangVien(string gv, string dv, string bm, string cm, string gvquoctich, string status)
        {
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var cmParameter = cm != null ?
                new ObjectParameter("cm", cm) :
                new ObjectParameter("cm", typeof(string));
    
            var gvquoctichParameter = gvquoctich != null ?
                new ObjectParameter("gvquoctich", gvquoctich) :
                new ObjectParameter("gvquoctich", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchGiangVien_Result>("SearchGiangVien", gvParameter, dvParameter, bmParameter, cmParameter, gvquoctichParameter, statusParameter);
        }
    
        public virtual ObjectResult<SearchHDDC_Result> SearchHDDC(string dc, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string lv, string gv, string status, string owner)
        {
            var dcParameter = dc != null ?
                new ObjectParameter("dc", dc) :
                new ObjectParameter("dc", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var ownerParameter = owner != null ?
                new ObjectParameter("owner", owner) :
                new ObjectParameter("owner", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHDDC_Result>("SearchHDDC", dcParameter, tungayParameter, denngayParameter, lvParameter, gvParameter, statusParameter, ownerParameter);
        }
    
        public virtual ObjectResult<SearchHDLV_Result> SearchHDLV(string hd, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string lv, string gv, string status, string owner)
        {
            var hdParameter = hd != null ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var ownerParameter = owner != null ?
                new ObjectParameter("owner", owner) :
                new ObjectParameter("owner", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHDLV_Result>("SearchHDLV", hdParameter, tungayParameter, denngayParameter, lvParameter, gvParameter, statusParameter, ownerParameter);
        }
    
        public virtual ObjectResult<SearchHocVien_Result> SearchHocVien(string hv, string cn, string nk, string status, string bm)
        {
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var cnParameter = cn != null ?
                new ObjectParameter("cn", cn) :
                new ObjectParameter("cn", typeof(string));
    
            var nkParameter = nk != null ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchHocVien_Result>("SearchHocVien", hvParameter, cnParameter, nkParameter, statusParameter, bmParameter);
        }
    
        public virtual ObjectResult<SearchLuanVan_Result> SearchLuanVan(string lv, string hv, string qd, string cm, string cn, string bm, string status, string owner)
        {
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var qdParameter = qd != null ?
                new ObjectParameter("qd", qd) :
                new ObjectParameter("qd", typeof(string));
    
            var cmParameter = cm != null ?
                new ObjectParameter("cm", cm) :
                new ObjectParameter("cm", typeof(string));
    
            var cnParameter = cn != null ?
                new ObjectParameter("cn", cn) :
                new ObjectParameter("cn", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var ownerParameter = owner != null ?
                new ObjectParameter("owner", owner) :
                new ObjectParameter("owner", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchLuanVan_Result>("SearchLuanVan", lvParameter, hvParameter, qdParameter, cmParameter, cnParameter, bmParameter, statusParameter, ownerParameter);
        }
    
        public virtual ObjectResult<string> SendMailSupport(string hv, string bm, string nk)
        {
            var hvParameter = hv != null ?
                new ObjectParameter("hv", hv) :
                new ObjectParameter("hv", typeof(string));
    
            var bmParameter = bm != null ?
                new ObjectParameter("bm", bm) :
                new ObjectParameter("bm", typeof(string));
    
            var nkParameter = nk != null ?
                new ObjectParameter("nk", nk) :
                new ObjectParameter("nk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SendMailSupport", hvParameter, bmParameter, nkParameter);
        }
    
        public virtual int Update_Result(string mahd, string lv, string gv, Nullable<float> diem, string danhgia)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            var gvParameter = gv != null ?
                new ObjectParameter("gv", gv) :
                new ObjectParameter("gv", typeof(string));
    
            var diemParameter = diem.HasValue ?
                new ObjectParameter("diem", diem) :
                new ObjectParameter("diem", typeof(float));
    
            var danhgiaParameter = danhgia != null ?
                new ObjectParameter("danhgia", danhgia) :
                new ObjectParameter("danhgia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Result", mahdParameter, lvParameter, gvParameter, diemParameter, danhgiaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Result_Duyet(string mahd, string lv)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var lvParameter = lv != null ?
                new ObjectParameter("lv", lv) :
                new ObjectParameter("lv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Result_Duyet", mahdParameter, lvParameter);
        }
    
        public virtual int UserRole(string action, string username, string tcode, string grantoption, string usergrant)
        {
            var actionParameter = action != null ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var tcodeParameter = tcode != null ?
                new ObjectParameter("tcode", tcode) :
                new ObjectParameter("tcode", typeof(string));
    
            var grantoptionParameter = grantoption != null ?
                new ObjectParameter("grantoption", grantoption) :
                new ObjectParameter("grantoption", typeof(string));
    
            var usergrantParameter = usergrant != null ?
                new ObjectParameter("usergrant", usergrant) :
                new ObjectParameter("usergrant", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserRole", actionParameter, usernameParameter, tcodeParameter, grantoptionParameter, usergrantParameter);
        }
    }
}
