//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string gv { get; set; }
        public string tcode { get; set; }
        public Nullable<bool> grantvoke { get; set; }
        public string usergrant { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual Tcode Tcode1 { get; set; }
    }
}
